# Основной docker-compose файл для разработки
# Использует dev-режим с auto-reload по умолчанию

# Загружаем переменные из config.env
env_file:
  - config.env

services:
  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    container_name: npo_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - npo_network
    restart: unless-stopped

  # FastAPI бэкенд (dev режим с auto-reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: npo_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app
    ports:
      - "${API_HOST}:${API_PORT}:8000"
    depends_on:
      - db
    networks:
      - npo_network
    restart: unless-stopped
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host ${API_HOST} --port 8000 --reload

  # Vue.js фронтенд (dev режим с hot-reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: npo_frontend
    ports:
      - "${API_HOST}:${FRONTEND_PORT}:5173"
    depends_on:
      - backend
    networks:
      - npo_network
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Nginx для проксирования (опционально)
  nginx:
    image: nginx:alpine
    container_name: npo_nginx
    ports:
      - "${API_HOST}:${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - npo_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  npo_network:
    driver: bridge