# Загружаем переменные из config.env
env_file:
  - config.env

services:
  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    container_name: npo_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - npo_network
    restart: unless-stopped

  # FastAPI бэкенд (продакшен)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: npo_backend_prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app
    ports:
      - "${API_HOST}:${API_PORT}:8000"
    depends_on:
      - db
    networks:
      - npo_network
    restart: unless-stopped
    command: uvicorn main:app --host ${API_HOST} --port 8000

  # Vue.js фронтенд (продакшен)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: npo_frontend_prod
    ports:
      - "${API_HOST}:${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - npo_network
    restart: unless-stopped

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    container_name: npo_nginx_prod
    ports:
      - "${API_HOST}:${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - npo_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  npo_network:
    driver: bridge
